version: "3.6"

services:
    grafana:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: grafana-development
        restart: unless-stopped
        environment:
            - TZ=Etc/UTC
            - GF_DEFAULT_INSTANCE_NAME=my-instance
            - GF_SECURITY_ADMIN_USER=owner
            - GF_LOG_MODE=console
            - GF_INSTALL_PLUGINS=${GF_INSTALL_PLUGINS}
            - GF_DATABASE_TYPE=${GF_DATABASE_TYPE}
            - GF_DATABASE_HOST=${GF_DATABASE_HOST}
            - GF_DATABASE_NAME=${GF_DATABASE_NAME}
            - GF_DATABASE_USER=${GF_DATABASE_USER}
            - GF_DATABASE_PASSWORD=${GF_DATABASE_PASSWORD}
            # - GF_DATABASE_SSL_MODE=disable # Change to "require" if Railway enforces SSL
        ports:
            - 3000:3000
        volumes:
            - ./data/grafana:/var/lib/grafana
        networks:
            - regenfass

networks:
    regenfass:
        name: regenfass
        driver: bridge
